export { default as Header } from './Layout/Header'
export { default as Footer } from './Layout/Footer'
export { default as PublicRoutes } from './PublicRoutes'
// Page Components 
export { default as Banner } from '../sections/home/Banner'
export { default as ClientSlides } from '../sections/home/ClientSlides'
export { default as AboutSec } from '../sections/home/AboutSec'
export { default as ServicesSec } from '../sections/home/ServicesSec'
export { default as PackagesSec } from '../sections/home/PackagesSec'
export { default as Testimonials } from '../sections/home/Testimonials'